// Generated by CoffeeScript 2.2.2
(function() {
  var Property;

  Property = class Property {
    static property(name, accessors) {
      return Object.defineProperty(this.prototype, name, accessors);
    }

  };

  module.exports = Property;

  //Object::property = (name, accessors) ->
//  Object.defineProperty @::, name, accessors

}).call(this);
