// Generated by CoffeeScript 2.2.2
(function() {
  var Accessory, Remote;

  Accessory = require('./Accessory');

  Remote = class Remote extends Accessory {};

  module.exports = Remote;

}).call(this);
