// Generated by CoffeeScript 2.2.2
(function() {
  var Property, Scene;

  Property = require('./Property');

  Scene = class Scene extends Property {
    constructor(scene) {
      var light;
      super();
      this.deleted = false;
      this.id = scene.instanceId;
      this.name = scene.name;
      this.predefined = scene.isPredefined;
      this.index = scene.sceneIndex;
      this.lights = (function() {
        var i, len, ref, ref1, results;
        ref1 = (ref = scene.lightSettings) != null ? ref : [];
        results = [];
        for (i = 0, len = ref1.length; i < len; i++) {
          light = ref1[i];
          results.push(light.instanceId);
        }
        return results;
      })();
    }

  };

  module.exports = Scene;

}).call(this);
