// Generated by CoffeeScript 2.2.2
(function() {
  var Accessory, Sensor;

  Accessory = require('./Accessory');

  Sensor = class Sensor extends Accessory {};

  module.exports = Sensor;

}).call(this);
